version: '3.7'
services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  ooking:
    image: booking_app
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    # Если не работает эта команда, используйте закомментированную
    command: [ "/booking/docker/app.sh" ]
    # command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

  celery:
    image: booking_celery
    build:
      context: .
    container_name: booking_celery
    # Если не работает эта команда, используйте закомментированную
    # command: ["/booking/docker/celery.sh", "celery"]
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  celery_beat:
    image: booking_celery
    build:
      context: . # celery это библиотека, у неё нет образа, берём из основного билда
    container_name: booking_celery_beat
    # Если не работает эта команда, используйте закомментированную
    # command: ["/booking/docker/celery.sh", "celery_beat"] # Второй аргумен для if/elif в скрипте
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO -B"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    image: booking_flower
    build:
      context: .
    container_name: booking_flower
    # Если не работает эта команда, используйте закомментированную
    # command: ["/booking/docker/celery.sh", "flower"]
    command: sh -c "celery --app=app.tasks.celery:celery flower"
    # При запуске через nginx необходимо запускать команду ниже для корректной работы js и css
    # command: sh -c "celery --app=app.tasks.celery:celery flower --url_prefix=/flower"
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - 5555:5555